name: test

on: [push]

permissions: read-all

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: code
        uses: actions/checkout@v4

      - name: go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.24

      - name: test
        run: go test -cover -coverprofile=coverage.out -covermode=atomic ./...

      - name: fuzz
        run: go test -list . | grep Fuzz | xargs -P 8 -I {} go test -fuzz {} -fuzztime 5s .
